### ISSUE TITLE
Error with imported docs that contain `$`

### ISSUE THREAD

**Issue by sloede** [analytech-solutions/CBindingGen.jl#15]
One of the C header files for which I used `CBindingGen.jl` contained `$` signs, which caused Julia to produce numerous errors like this
```julia
syntax: invalid interpolation syntax: "$ "
```
Is there a way to disable comment generation and/or to automatically convert `$` in docstrings to something innocuous(, e.g., `` ` ``)?

**Comment by krrutkow** [comment]
Yes, you can disable comment generation by using the `comments = false` keyword argument for the generate function.  CBindingGen should escape `$` though like it does with `"`.

**Comment by sloede** [comment]
Thanks, the `comments=false` keyword argument works as expected.

Regarding the escaping of `$`: Are you referring to these lines:
https://github.com/analytech-solutions/CBindingGen.jl/blob/1043a00b2b0176fe213b426ba895faea217d7802/src/generate.jl#L31-L35

If yes, I see how `"` is escaped, but I fail to see where it is done for `$`.

**Comment by krrutkow** [comment]
Sorry, I meant to say "CBindingGen should [be changed to] escape `$`..."

**Comment by sloede** [comment]
I created #17 to fix this (sorry for the double PR, I got some whitespace mixup...)
