### ISSUE TITLE
Confusion between macro and function

### ISSUE THREAD

**Issue by jessymilare** [analytech-solutions/CBindingGen.jl#20]
I created some code to generate bindings for GNU Gettext library and it generated incorrect bindings. Any C macro that expands to a function name is translated into a Julia macro that expands to another macro. For instance:

```julia
	𝐣𝐥.@doc """
	## Reference
	
	[libintl.h:358](./..\\..\\..\\..\\.julia\\artifacts\\c38e0f0854753b42d208bf7f62aafa3100ba3880\\include\\libintl.h:358:10)
	""" :(@libintl_printf)
	export @libintl_printf
	macro libintl_printf() return quote (@__printf__) end end

        # [...]

	𝐣𝐥.@doc """
	```
	𝐣𝐥.@cextern __printf__(var\"?1?\"::𝐣𝐥.Ptr{𝐣𝐥.Cconst(𝐣𝐥.Cchar)}, var\"?vararg?\"...)::𝐣𝐥.Cint
	```
	
	## Reference
	
	[libintl.h:361](./..\\..\\..\\..\\.julia\\artifacts\\c38e0f0854753b42d208bf7f62aafa3100ba3880\\include\\libintl.h:361:12)
	""" __printf__

	𝐣𝐥.@cextern __printf__(var"?1?"::𝐣𝐥.Ptr{𝐣𝐥.Cconst(𝐣𝐥.Cchar)}, var"?vararg?"...)::𝐣𝐥.Cint

```

But the macro `@__printf__` doesn't exist:

```julia
julia> LibGettext.@libintl_printf
ERROR: UndefVarError: @__printf__ not defined
```

The same problem occurs with `gettext`, `ngettext`, etc.

**Comment by krrutkow** [comment]
Yes, macros are definitely the most evil part of C, and unfortunately a lot of libraries use macros to mask functions and types.  There is not a very clear universal way to handle macros, so you will need to handle them on your own.  You can filter out the problematic macro definitions with the filter function passed to `convert_headers` using something like:
```jl
  if cursor.kind == LibClang.CXCursor_MacroDefinition && startswith(string(cursor), "libintl_")
    push!(deal_with_later, cursor)
    return false
  end
```

Then add those definitions manually to the result of `convert_headers` (actual conversion might be much more complex that what is shown here):
```jl
for cursor in deal_with_later
  name = string(cursor)
  actual = "__"*name[length("libintl_")+1:end]*"__"
  cvt = Converted("const $(name) = $(actual)", Dict{String, CBindingGen.Comment}())
  push!(cvts, cvt)
end
```

Finally, call `generate` to create the bindings.

**Comment by krrutkow** [comment]
CBinding.jl v1 support for macros and functions should now avoid this situation entirely.
